name: Restrict Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Only 'develop' branch can merge into main!"
            exit 1
          fi
